# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Travis Runyard
title: Systems Administrator
email: travisrunyard@gmail.com
phone: 714-260-7352
website: https://sysinfo.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: travisrunyard
github_username:  visualblind
stackoverflow_username: "3773019"
# dribbble_username: jekyll
#facebook_username: trunyard
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: travisrunyard
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Summary
about_profile_image: images/profile-white.jpg
about_content: | # this will include new lines to allow paragraphs
  Systems Administrator with 13 years of experience in the semiconductor, logistics, finance, web development and service industries with a natural unavoidable attention to detail.

  Certifications: <mark>MCSA</mark>, <mark>Network+</mark>, <mark>A+</mark>

  - Well rounded in all aspects of core IT Infrastructure and best practices
  - 24/7/365 on-call standby resource responsibility for urgent IT incidents
  - Proficient in managing all major flavors of Linux operating systems
  - Over 13 years of Wintel experience
  - Knowledge of public internet and internal network protocols
  - Microsoft Active Directory & Exchange migration experience
  - Process Automation & Scripting expertise
  - Technical Support, Systems Installation, Configuration & Upgrading
  - Microsoft SQL Server and MySQL Database Administration
  - Disaster Recovery Planning RTO/RPO, updating & patch management
  - Authorized to work in the US for any employer

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Robert Half
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Systems Administrator
        caption: November 2018 - December 2018
        quote: >
          Provided capacity to streamline and refine existing standard procedures including automation of end user Office365 email signature generation and deployment, reduce capital expenditure in AWS cloud, and focus on project-oriented tasks, which affect the whole organization.
        description: | # this will include new lines to allow paragraphs
          - Plan, deploy, and manage IT systems: Windows Servers, Hyper-V Clustering, Active Directory, Exchange, Office 365 AD Integration
          - Acknowledge and respond to all assigned service tickets within the SLA
          - Assure the performance and availability of all systems in multiple states
          - Troubleshoot and perform break-fix tasks on all systems
          - Document maintenance for all systems and network infrastructure
          - Maintain Active Directory infrastructure including implementation of new features
          - Provide support for Microsoft technologies (DFS, DHCP, Active Directory, Exchange, RDS, Windows Server 2008/2012/R2, SQL Server)
          - Provide support services for virtualization technologies: Hyper-V, and ESXi, and use best practices to implement and maintain the hardware environment
          - Monitor the remote management system alerts & notifications
          - Administer and maintain the remote monitoring and management system: updates agent scripts, responds to alerts, and monitors dashboard
          - Inspect the use of technology and software to ensure functionality and efficiency
          - Identify the need for upgrades, configurations or new systems
          - Handle or assist in equipment moves, deployment, equipment tracking, requisitions, and/or RMAs
          - Communicate effectively to users and IT resources to help understand or effectively troubleshoot issues or requests
          - Provide networking diagnostics (IP network routing, DNS, DHCP)
          - Perform TCP/IP, LAN/WAN, network and related troubleshooting diagnostics and repair

      - layout: left
        title: SchoolsFirst Federal Credit Union
        link: https://www.schoolsfirstfcu.org/
        link_text: schoolsfirstfcu.org
        sub_title: Systems Administrator I
        caption: August 2017 - March 2018
        quote: >
          Support complex heavily virtualized VMware infrastructure with a focus in key functional areas including applications, operating systems, servers, storage and virtualization.
        description: | # this will include new lines to allow paragraphs
          - Manage corporate SSL/TLS certificates/keys via Venafi PKI (public key infrastructure) software
          - Support complex infrastructure with a focus in key functional areas including applications, operating systems, servers, storage and virtualization
          - Microsoft Active Directory, Microsoft Exchange, Microsoft IIS, Microsoft SQL, Microsoft Skype for Business
          - Install and configure systems and virtual machines to support infrastructure and applications on VMWare vSphere 6.x technologies
          - Coordinate with vendors for technical support and upgrades
          - Submit and fulfill ServiceNow ITSM service requests, respond to incidents and problems
          - Perform daily systems monitoring with Solar Winds NPM, Splunk
          - Verify the integrity and availability of all hardware, server resources, systems and key processes, reviewing system and application logs, and verifying completion of after-hours maintenance
          - Gather and analyze Wintel/RHEL and IBM FileNet application log files
          - Provide second tier support including investigation and troubleshooting
          - Perform regular systems hardening to maintain security standards
          - Schedule, test, stage, deploy Wintel updates for all prod virtual machines with IBM BigFix
          - Support Credit Union specific backend and general back office applications
          - IBM Tivoli Storage Manager backup software administration
          - Cisco UCS B/C Class, HP Non-Stop, IBM P Series, Nutanix

      - layout: left
        title: Rhythm Agency
        link: https://rhythmagency.com/
        link_text: rhythmagency.com
        sub_title: Systems Engineer
        caption: February 2016 - May 2017
        quote: >
          Provide 75% Linux / 25% Windows administration, LAN/WAN/VPN administration, VMware administration, and extensive exposure to Amazon Web Services. Manage company infrastructure while deploying and managing client Microsoft .NET (Umbraco), LAMP and LEMP stacks running Wordpress. Manage high availability (HA) and disaster recovery (DR) solutions with SQL Server Availability Groups and AWS EC2 snapshots.
        description: | # this will include new lines to allow paragraphs
          - Consolidated virtual machines on AWS EC2 while migrating from Digital Ocean and various other cloud providers
          - Managed Linux Ubuntu Server, Windows Server 2008/2016 and Active Directory infrastructure
          - Decreased OPEX by defining a more manageable storage solution by defining a better snapshot schedule system
          - Tuned OS, front and back-end business applications: Apache and MySQL on all systems according to system resources (http://bit.ly/2r4e7Xu)
          - Worked with entire Atlassian product suite (JIRA, Bit Bucket, Confluence, Trello, HipChat)
          - Created and maintain IT standard operating procedures using Atlassian Confluence
          - Used as much of AWS's services where possible including EC2, VPC, Route 53, SES in an effort to centralize management of company and infrastructures
          - Implemented Cloudflare business plans to utilize WAF and CDN for customers who receive high web traffic (250,000+ unique visitors/month)
          - Manage all infrastructure and client websites Apex score with New Relic SaaS
          - Researched, recommended and implemented network enhancements that improved system reliability and performance including ISC DNS (BIND) & DHCP
          - SSL purchasing, implementation and hardening against known vulnerabilities on Linux and Windows servers
          - Act as point of first contact for all internal Mac and PC issues

      - layout: left
        title: Sentric
        link: https://sentrichr.com/
        link_text: sentrichr.com
        sub_title: Systems Administrator
        caption: April 2011 - January 2016
        quote: >
          Provide 90% Windows / 10% Linux administration, LAN/WAN/VPN administration, internal VMware administration, and extensive exposure to Amazon Web Services although we eventually migrated away from AWS. Manage company infrastructure while deploying and managing client Microsoft .NET HR-related web portals. Manage disaster recovery (DR) solutions for mission critical and client systems.
        description: | # this will include new lines to allow paragraphs
          - Wear multiple hats: Windows and Linux System Engineer, Network Administrator, VMware Administrator, SAN Administrator, Desktop Support
          - Active Directory domain and Exchange Server migration to Amazon EC2
          - Plan and implement disaster recovery for mission critical SQL database systems
          - Ensure sufficient compute and storage capacity for Windows and SQL servers
          - Monitor SQL server performance using Perfmon metrics and PAL for analysis
          - Design and implement the Active Directory infrastructure including DNS, DHCP, CA, NPS, GPO, WINS, DFS/DFSS, WSUS, WDS, backups and reporting
          - Implement Distributed File System Replication
          - Develop a PHP and MySQL based infrastructure status display
          - Server monitoring with Nagios configurations and plugins
          - Maintain LAMP stack including WordPress
          - SSL certificate process for Windows and Linux servers
          - Deploy VPN network routing and addressing in Amazon VPC
          - Deploy SSTP remote access VPN with Group Policy
          - Setup and deploy virtual machines running in Amazon EC2
          - Automate Active Directory reporting and user account lockout event notification, internal processes and Outlook MAPI user profiles with PowerShell and Group Policy
          - Use AWS Tools for Windows PowerShell to automate scheduled AMI backups
          - Sonicwall IPSEC VPN setup between offices
          - Maintain Exchange Server email system
          - Troubleshoot critical performance issues (SQL Server, SAN)
          - SAN support (firmware and driver updates, partition alignment, cluster size, iSCSI)
          - Configured WiFi WPA2-Enterprise with NPS RADIUS
          - Communicate with outside service centers and software vendors

      - layout: left
        title: Agility Logistics
        link: https://www.agility.com/
        link_text: agility.com
        sub_title: Network Support
        caption: April 2008 - May 2010
        quote: >
          Provide 90% Windows / 10% Linux administration. Travel required between offices in L.A. and O.C. 60/40 split between server/client responsibilities.
        description: | # this will include new lines to allow paragraphs
          - Monitor on-site and remote servers for maintenance and troubleshoot issues at the operating system, hardware and network layers utilizing Nagios and HP Insite Mgr
          - Administer tape backups on and off-site of all business critical servers in the corporate office. Design CA Arcserve efficiently backing up 60 servers which include Exchange, SQL, Oracle, MS and Linux systems.
          - Install, support, monitor Exchange severs with over 2,000 mailboxes.
          - Configure and update BIND DNS and Nagios running RHEL operating system according to infrastructure changes.
          - Write SOP documentation pertaining to the IT infrastructure.
          - Assist with the planning and implementation of various projects as required.
          - Build, maintain and support company standard images for client laptop and desktop PCs
          - Build, configure, support physical and virtual Windows 2000/2003/2008 operating systems on various platforms including: HP Proliant, IBM BladeCenter, System X, Dell PowerEdge, Citrix Xenserver, VMware ESXi

      - layout: left
        title: Broadcom
        link: https://www.broadcom.com/
        link_text: broadcom.com
        sub_title: L2 Wintel Helpdesk
        caption: March 2006 - October 2007
        quote: >
          Full time contact position. Provide 95% Windows / 5% Linux support, LAN/VPN administration. Originally hired as a Level I Wintel Helpdesk Technician but quickly moved up to Level II. Operated on a team of 8 providing 24/7 support to a Fortune 500 client with a campus supporting over 500 internal employees.
        description: | # this will include new lines to allow paragraphs
          - Support world-wide combined total of 7,800+ end users in a closed intranet Windows enterprise environment
          - Deploy applications using Altiris software and troubleshoot all on-campus end user PC's (mostly Windows)
          - Move users' stations and routine procedures on Avaya telecom backend
          - Escalate server issues to Level III Wintel business unit when necessary
          - Day to day duties include using Remedy helpdesk software for incident resolution and software/ hardware inventory management
          - Train and coach entry-level technical candidates. Designated as direct support for Directors and VP's in an extremely demanding environment
          - Prepare and image enterprise x86/x64 systems for end users, installation of all nonstandard hardware, software and configuration
          - Remotely diagnose and resolve requests utilizing Altiris and other remote tools (Carbon Copy, VNC, RDP)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Active Directory & Exchange Migration Project
        link: https://sysinfo.io/active-directory-migration-2003-2008-r2/
        link_text: sysinfo.io/active-directory-migration-2003-2008-r2
        additional_links:
          - title:  Active Directory Migration
            icon: fab fa-exchange-alt
            url: https://sysinfo.io/active-directory-migration-2003-2008-r2/
          - title:  Project site
            icon: fas fa-server
            url: https://sysinfo.io/active-directory-migration-2003-2008-r2/
        quote: >
          Planned, prepared and implemented an Active Directory interforest migration from domain functional level 2003 to 2008R2 with an Exchange mailbox migration from 2007 to 2010.
        description: | # this will include new lines to allow paragraphs
          A few years ago in a past life I got to perform an Active Directory migration from a 2003 functional level to 2008 R2 with ADMT 3.2 accompanied with an Exchange Server 2007 to 2010 migration over a single weekend. I thoroughly documented every step of the process and it's available at the link above. 

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      - layout: left
        #title:
        #caption:
        #sub_title:
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          - System Administration (x86_64)
          - Network Administration (LAN/WAN)
          - AWS (IAM, EC2, CloudWatch, VPC, S3, RDS, SES, Route53)
          - Bugchecking & root cause analysis (sysinternals)
          - VMware vSphere/vCenter/ESXi 5.x-6.x
          - Active Directory
          - Windows Server (2003-2019)
          - Shell scripting (Bash/Python)
          - Batch (csh) scripting (Wintel)
          - Microsoft PowerShell
          - Linux Administration
          - DNS (BIND/Microsoft)
          - MCSA, Network+, A+
          - Certifications: MCSA, Network+, A+
        **General:
          - Amazon Web Services AWS (EC2, VPC, S3, RDS, SES, Route 53,billing and cost calculation), Active Directory, SMTP, SAN, DNS, WINS, DHCP, Terminal Services/Remote Desktop Services, Continuous Integration, Infrastructure as Code, New Relic, Atlassian Suite (Confluence/JIRA/BitBucket/HipChat/Trello)
        >Client OS:
          - DOS, Ubuntu, Apple OSX, Windows NT/XP/7/8/10
        Server OS:
          - Windows Server (2003, 2008, 2012, 2016), Debian/Ubuntu, RedHat/CentOS/Fedora, VMWare ESXi/vCenter/vSphere 4x-6x
        Software (NT):
          - AWS Powershell, Active Directory, Blackberry BES, CA ARCserve Backup, CA eTrust Server, Citrix XenServer, Citrix Metaframe/Presentation Server/XenApp 6.5, Exchange Server 2010-2013, Idera SQLSafe/Diagnostic Manager/Fragmentation Analyzer,  Internet Information Services (IIS), Microsoft SQL Server 2000-2016 (exp, std, ent), RAS, Sysinternals, Trend Micro Server, Veritas BackupExec, Veeam Backup and Replication, Microsoft System Center Configuration Manager (SCCM) 2012
        Software (Linux):
          - Nagios & NRPE, Zenoss, PRTG, Postfix, Ansible, Apache, NGINX, FPM-CGI, MySQL, MariaDB, PostgreSQL, SSH, EC2 API tools, Docker, Kubernetes, SolarWinds NPM, Syslog, bash, sysVinit, Systemd, sed, awk


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
